# -*- coding: utf-8 -*-
"""Solid_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWzMGZFpYT4X9NKUXU4o5i7dKG4IFK5o
"""

# Ứng dụng Phân loại Đất Trồng sử dụng Perceptron
# Cài đặt và import thư viện
!pip install ipywidgets -q

import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import ipywidgets as widgets
from IPython.display import display, clear_output, HTML
import warnings
warnings.filterwarnings('ignore')
# Dữ liệu thực tế
# Thứ tự: [pH, Nitrogen, Phosphorus, Potassium, Temperature, Humidity, Rainfall]
data_real = np.array([
    [6.2, 1.6, 15, 130, 28, 70, 1500],   # Lúa
    [6.5, 1.8, 18, 140, 26, 65, 1700],   # Lúa
    [7.0, 2.0, 23, 150, 30, 55,  900],   # Ngô
    [6.8, 2.2, 22, 160, 27, 50,  800],   # Ngô
    [5.5, 1.2, 28, 150, 22, 80,  700],   # Rau màu
    [6.0, 1.5, 30, 140, 18, 75,  600],   # Rau màu
    [6.5, 1.4, 18, 145, 16, 60,  500],   # Lúa mì
    [7.2, 1.6, 22, 150, 15, 55,  700],   # Lúa mì
    [5.8, 1.6, 35, 160, 18, 70,  800],   # Khoai tây
    [6.0, 1.8, 40, 180, 17, 65, 1000],   # Khoai tây
])

# Nhãn tương ứng (Label)
labels_real = np.array([0, 0, 1, 1, 3, 3, 2, 2, 4, 4])  # 0=Lúa, 1=Ngô, 2=Lúa mì, 3=Rau màu, 4=Khoai tây

# Tạo dữ liệu mô phỏng phân loại đất trồng
def create_soil_dataset(n_samples=300):
    """
    Tạo dữ liệu mô phỏng để phân loại loại cây trồng phù hợp
    Features: pH, Nitrogen, Phosphorus, Potassium, Temperature, Humidity, Rainfall
    Labels: 0=Rice(Lúa), 1=Corn(Ngô), 2=Wheat(Lúa mì), 3=Vegetables(Rau), 4=Potato(Khoai tây)
    """
    np.random.seed(42)

# Mở rộng dữ liệu thực tế để tạo dữ liệu mô phỏng lớn hơn
    X = []
    y = []
    for _ in range(n_samples // len(data_real)):
        X.extend(data_real)
        y.extend(labels_real)

# Convert to NumPy arrays
    X = np.array(X)
    y = np.array(y)

# Đảm bảo giá trị trong phạm vi hợp lý (Dựa trên quan sát từ dữ liệu thực tế và miền giá trị phổ biến)
    X[:, 0] = np.clip(X[:, 0], 5.0, 8.0)  # pH (5.0 - 8.0)
    X[:, 1] = np.clip(X[:, 1], 0.5, 3.0)  # Nitrogen (%) (0.5 - 3.0)
    X[:, 2] = np.clip(X[:, 2], 10, 60)    # Phosphorus (mg/kg) (10 - 60)
    X[:, 3] = np.clip(X[:, 3], 50, 300)   # Potassium (mg/kg) (50 - 300)
    X[:, 4] = np.clip(X[:, 4], 15, 35)    # Temperature (°C) (15 - 35)
    X[:, 5] = np.clip(X[:, 5], 40, 90)    # Humidity (%) (40 - 90)
    X[:, 6] = np.clip(X[:, 6], 50, 2000)  # Rainfall (mm) (50 - 2000) # Adjusted max rainfall
    return X, y
# Huấn luyện mô hình Perceptron
print("Đang tạo dữ liệu và huấn luyện mô hình...")

# Tạo dữ liệu mô phỏng lớn hơn: [data augmentation (tăng cường dữ liệu)]
X, y = create_soil_dataset(n_samples=300) # Generate 300 samples

# Chia dữ liệu (adjusted test_size)
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42, stratify=y )

model = make_pipeline(StandardScaler(), Perceptron(max_iter=1000, tol=1e-3, random_state=42))
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print(f"Huấn luyện xong! Độ chính xác: {accuracy:.2%}")
# Hiển thị dữ liệu mẫu (showing first 10 samples of generated data)
feature_names = ['pH', 'Nitrogen(%)', 'Phosphorus(mg/kg)', 'Potassium(mg/kg)',
                'Temperature(°C)', 'Humidity(%)', 'Rainfall(mm)']
crop_names = {0:'Lúa', 1:'Ngô', 2:'Lúa mì', 3:'Rau củ', 4:'Khoai tây'}

df = pd.DataFrame(X[:10], columns=feature_names)
df['Loại cây trồng'] = [crop_names[label] for label in y[:10]]

print("\nDữ liệu ban đầu dùng để tăng cường và đưa vào huấn luyện :")
display(df.round(2))
# CSS styling
html_style = """
<style>
.widget-container {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    padding: 25px;
    border-radius: 15px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.3);
    margin: 15px 0;
}
.prediction-result {
    background: linear-gradient(135deg, #4CAF50, #45a049);
    color: white;
    padding: 25px;
    border-radius: 15px;
    text-align: center;
    font-size: 20px;
    font-weight: bold;
    margin-top: 20px;
    box-shadow: 0 8px 25px rgba(76, 175, 80, 0.3);
}
.crop-info {
    background: rgba(255,255,255,0.95);
    padding: 20px;
    border-radius: 12px;
    margin: 15px 0;
    border-left: 6px solid #4CAF50;
    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
}
.widget-slider .widget-label {
    font-size: 16px !important;
    font-weight: 600 !important;
    color: #2c3e50 !important;
    min-width: 200px !important;
}
.widget-slider .widget-readout {
    font-size: 15px !important;
    font-weight: bold !important;
    background: #34495e !important;
    color: white !important;
    padding: 5px 12px !important;
    border-radius: 8px !important;
    min-width: 80px !important;
}
.widget-slider {
    margin: 15px 0 !important;
}
/* BUTTON STYLING */
.widget-button {
    font-size: 18px !important;
    font-weight: bold !important;
    padding: 15px 30px !important;
    border-radius: 12px !important;
    box-shadow: 0 5px 15px rgba(76, 175, 80, 0.3) !important;
}
</style>
"""
display(HTML(html_style))

header = widgets.HTML(
    value="""
    <div style='background: linear-gradient(135deg, #4CAF50, #45a049);
                color: white; padding: 25px; border-radius: 15px;
                text-align: center; margin-bottom: 25px;
                box-shadow: 0 8px 25px rgba(76, 175, 80, 0.3);'>
        <h2 style='font-size: 28px; margin-bottom: 10px;'>🌱 HỆ THỐNG PHÂN LOẠI ĐẤT TRỒNG TRỌT</h2>
        <p style='font-size: 18px;'>Tùy chỉnh thông số đất để dự đoán loại cây trồng phù hợp</p>
    </div>
    """
)

# Tạo slider
slider_layout = widgets.Layout(width='450px', height='40px')
slider_style = {'description_width': '180px'}

ph_slider = widgets.FloatSlider(
    value=6.5, min=5.0, max=8.0, step=0.1,
    description='🧪 pH:',
    layout=slider_layout,
    style=slider_style
)

nitrogen_slider = widgets.FloatSlider(
    value=1.8, min=0.5, max=3.0, step=0.1,
    description='🧬 Nitrogen (%):',
    layout=slider_layout,
    style=slider_style
)

phosphorus_slider = widgets.FloatSlider(
    value=30, min=10, max=60, step=1,
    description='⚡ Phosphorus (mg/kg):',
    layout=slider_layout,
    style=slider_style
)

potassium_slider = widgets.FloatSlider(
    value=150, min=50, max=300, step=5,
    description='🔋 Potassium (mg/kg):',
    layout=slider_layout,
    style=slider_style
)

temperature_slider = widgets.FloatSlider(
    value=25, min=15, max=35, step=0.5,
    description='🌡️ Nhiệt độ (°C):',
    layout=slider_layout,
    style=slider_style
)

humidity_slider = widgets.FloatSlider(
    value=65, min=40, max=90, step=1,
    description='💧 Độ ẩm (%):',
    layout=slider_layout,
    style=slider_style
)

rainfall_slider = widgets.FloatSlider(
    value=800, min=50, max=2000, step=50,
    description='🌧️ Lượng mưa (mm):',
    layout=slider_layout,
    style=slider_style
)

# Nút dự đoán
predict_button = widgets.Button(
    description='Dự Đoán Loại Cây Trồng',
    button_style='success',
    layout=widgets.Layout(width='350px', height='60px'),
    style={'font_weight': 'bold'}
)

output = widgets.Output()

# Hàm dự đoán
def predict_crop(b):
    with output:
        clear_output()
        input_data = np.array([[
            ph_slider.value, nitrogen_slider.value, phosphorus_slider.value,
            potassium_slider.value, temperature_slider.value,
            humidity_slider.value, rainfall_slider.value
        ]])
        prediction = model.predict(input_data)[0]
        crop_dict = {0:"🌾 LÚA", 1:"🌽 NGÔ", 2:"🌾 LÚA MÌ", 3:"🥬 RAU CỦ", 4:"🥔 KHOAI TÂY"}
        confidence = model.decision_function(input_data)[0]
        predicted_crop_name = crop_dict[prediction]

# Thông tin về cây trồng
        crop_info_detailed = {
            0: "Lúa thích hợp điều kiện ẩm ướt, cần nhiều nước và độ ẩm cao. Thích hợp trồng ở vùng đồng bằng.",
            1: "Ngô cần nhiều Nitrogen, đất thoát nước tốt, khí hậu ấm. Phù hợp vùng đồi núi và đồng bằng.",
            2: "Lúa mì thích hợp khí hậu mát mẻ, khô ráo, cần ít nước. Thích hợp vùng cao và mùa đông.",
            3: "Rau củ đa dạng, cần nhiều dinh dưỡng, đất tơi xốp. Có thể trồng quanh năm với chăm sóc tốt.",
            4: "Khoai tây ưa khí hậu mát, đất tơi xốp hơi chua (pH ~5.5–6.5). Thích hợp vùng cao và mùa mát."
        }
        crop_description = crop_info_detailed.get(prediction, "Thông tin chưa có.")

        result_html = f"""
<div class="prediction-result">
            <h2 style="font-size: 24px; margin-bottom: 15px;"> KẾT QUẢ DỰ ĐOÁN</h2>
            <h1 style="font-size: 3em; margin: 15px 0; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">{predicted_crop_name}</h1>
            <p style="font-size: 18px; opacity: 0.9;">(Độ tin cậy: {abs(np.max(confidence)):.2f})</p>
        </div>
        <div class="crop-info">
            <h3 style="color: #2e7d32; margin-bottom: 15px; font-size: 20px;">📝 Mô tả chi tiết:</h3>
            <p style="font-size: 16px; line-height: 1.6;">{crop_description}</p>
        </div>
        <div class="crop-info">
            <h3 style="color: #1976d2; margin-bottom: 15px; font-size: 20px;">📊 Thông số đầu vào:</h3>
            <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; font-size: 15px;">
                <div style="padding: 8px; background: #f8f9fa; border-radius: 8px;"><strong>🧪 pH:</strong> {ph_slider.value}</div>
                <div style="padding: 8px; background: #f8f9fa; border-radius: 8px;"><strong>🧬 Nitrogen:</strong> {nitrogen_slider.value}%</div>
                <div style="padding: 8px; background: #f8f9fa; border-radius: 8px;"><strong>⚡ Phosphorus:</strong> {phosphorus_slider.value} mg/kg</div>
                <div style="padding: 8px; background: #f8f9fa; border-radius: 8px;"><strong>🔋 Potassium:</strong> {potassium_slider.value} mg/kg</div>
                <div style="padding: 8px; background: #f8f9fa; border-radius: 8px;"><strong>🌡️ Nhiệt độ:</strong> {temperature_slider.value}°C</div>
                <div style="padding: 8px; background: #f8f9fa; border-radius: 8px;"><strong>💧 Độ ẩm:</strong> {humidity_slider.value}%</div>
                <div style="padding: 8px; background: #f8f9fa; border-radius: 8px; grid-column: 1/-1;"><strong>🌧️ Lượng mưa:</strong> {rainfall_slider.value} mm</div>
            </div>
        </div>
        """
        display(HTML(result_html))

predict_button.on_click(predict_crop)

# Layout giao diện
left_column = widgets.VBox([
    ph_slider,
    nitrogen_slider,
    phosphorus_slider,
    potassium_slider
], layout=widgets.Layout(padding='10px'))

right_column = widgets.VBox([
    temperature_slider,
    humidity_slider,
    rainfall_slider,
    widgets.HTML("<div style='height: 55px;'></div>")  # Spacer cân bằng
], layout=widgets.Layout(padding='10px'))

sliders_layout = widgets.HBox([left_column, right_column],
                             layout=widgets.Layout(justify_content='space-around'))

ui = widgets.VBox([
    header,
    sliders_layout,
    widgets.HTML("<div style='text-align: center; margin: 20px 0;'></div>"),
    predict_button,
    output
], layout=widgets.Layout(padding='20px'))

display(ui)
